spring.application.name=fastbuy

#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.url=jdbc:postgresql://82.25.69.177:5433/yanzinventory

#spring.datasource.username=postgres
#spring.datasource.password=dba
spring.datasource.username=yanz
spring.datasource.password=1kariS223

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Directorio donde se guardaran las imagenes
app.upload.dir=uploads/images

# OpenAI Configuration
openai.api.key="apikey"
# File Size limits para subida de imagenes (por defecto Spring da error en +1MB)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# n8n Configuration
n8n.webhook.url=https://n8n.yanz-academy.online/webhook/main
n8n.api.token="api_n8n"
